#ifndef CONSOLE_MACROS_H_
#define CONSOLE_MACROS_H_

/*
 * Fields marked with [#] must be set by the low-level driver.
 * Fields marked with [!] can be changed by the low-level driver
 * to achieve effects such as fast scrolling by changing the origin.
 */

#define CONS_NUM          (m_VirtualConsole[currcons].d.num)
#define SW                (m_VirtualConsole[currcons].d.sw)
#define SCREENBUF         (m_VirtualConsole[currcons].d.screenbuf)
#define SCREENBUF_SIZE    (m_VirtualConsole[currcons].d.screenbuf_size)
#define ORIGIN            (m_VirtualConsole[currcons].d.origin)
#define SCR_TOP           (m_VirtualConsole[currcons].d.scr_top)
#define VISIBLE_ORIGIN    (m_VirtualConsole[currcons].d.visible_origin)
#define SCR_END           (m_VirtualConsole[currcons].d.scr_end)
#define POS               (m_VirtualConsole[currcons].d.pos)
#define TOP               (m_VirtualConsole[currcons].d.top)
#define BOTTOM            (m_VirtualConsole[currcons].d.bottom)
#define X                 (m_VirtualConsole[currcons].d.x)
#define Y                 (m_VirtualConsole[currcons].d.y)
#define VC_STATE          (m_VirtualConsole[currcons].d.state)
#define NPAR              (m_VirtualConsole[currcons].d.npar)
#define PAR               (m_VirtualConsole[currcons].d.par)
#define QUES              (m_VirtualConsole[currcons].d.ques)
#define ATTR              (m_VirtualConsole[currcons].d.attr)
#define SAVED_X           (m_VirtualConsole[currcons].d.saved_x)
#define SAVED_Y           (m_VirtualConsole[currcons].d.saved_y)
#define TRANSLATE         (m_VirtualConsole[currcons].d.translate)
#define G0_CHARSET        (m_VirtualConsole[currcons].d.g0_charset)
#define G1_CHARSET        (m_VirtualConsole[currcons].d.g1_charset)
#define SAVED_G0          (m_VirtualConsole[currcons].d.saved_g0)
#define SAVED_G1          (m_VirtualConsole[currcons].d.saved_g1)
#define UTF               (m_VirtualConsole[currcons].d.utf)
#define UTF_COUNT         (m_VirtualConsole[currcons].d.utf_count)
#define UTF_CHAR          (m_VirtualConsole[currcons].d.utf_char)
#define VIDEO_ERASE_CHAR  (m_VirtualConsole[currcons].d.video_erase_char)
#define DISP_CTRL         (m_VirtualConsole[currcons].d.disp_ctrl)
#define TOGGLE_META       (m_VirtualConsole[currcons].d.toggle_meta)
#define DECSCNM           (m_VirtualConsole[currcons].d.decscnm)
#define DECOM             (m_VirtualConsole[currcons].d.decom)
#define DECAWM            (m_VirtualConsole[currcons].d.decawm)
#define DECCM             (m_VirtualConsole[currcons].d.deccm)
#define DECIM             (m_VirtualConsole[currcons].d.decim)
#define DECCOLM           (m_VirtualConsole[currcons].d.deccolm)
#define NEED_WRAP         (m_VirtualConsole[currcons].d.need_wrap)
#define KMALLOCED         (m_VirtualConsole[currcons].d.kmalloced)
#define REPORT_MOUSE      (m_VirtualConsole[currcons].d.report_mouse)
#define COLOR             (m_VirtualConsole[currcons].d.color)
#define S_COLOR           (m_VirtualConsole[currcons].d.s_color)
#define DEF_COLOR         (m_VirtualConsole[currcons].d.def_color)
#define FOREGROUND        (COLOR & 0x0f)
#define BACKGROUND        (COLOR & 0xf0)
#define CHARSET           (m_VirtualConsole[currcons].d.charset)
#define S_CHARSET         (m_VirtualConsole[currcons].d.s_charset)
#define INTENSITY         (m_VirtualConsole[currcons].d.intensity)
#define UNDERLINE         (m_VirtualConsole[currcons].d.underline)
#define BLINK             (m_VirtualConsole[currcons].d.blink)
#define REVERSE           (m_VirtualConsole[currcons].d.reverse)
#define S_INTENSITY       (m_VirtualConsole[currcons].d.s_intensity)
#define S_UNDERLINE       (m_VirtualConsole[currcons].d.s_underline)
#define S_BLINK           (m_VirtualConsole[currcons].d.s_blink)
#define S_REVERSE         (m_VirtualConsole[currcons].d.s_reverse)
#define ULCOLOR           (m_VirtualConsole[currcons].d.ulcolor)
#define HALFCOLOR         (m_VirtualConsole[currcons].d.halfcolor)
#define TAB_STOP          (m_VirtualConsole[currcons].d.tab_stop)
#define PALETTE           (m_VirtualConsole[currcons].d.palette)
#define BELL_PITCH        (m_VirtualConsole[currcons].d.bell_pitch)
#define BELL_DURATION     (m_VirtualConsole[currcons].d.bell_duration)
#define CURSOR_TYPE       (m_VirtualConsole[currcons].d.cursor_type)
#define DISPLAY_FG        (m_VirtualConsole[currcons].d.display_fg)
#define COMPLEMENT_MASK   (m_VirtualConsole[currcons].d.complement_mask)
#define S_COMPLEMENT_MASK (m_VirtualConsole[currcons].d.s_complement_mask)
#define HI_FONT_MASK      (m_VirtualConsole[currcons].d.hi_font_mask)

#endif /* console_macros_H_ */
